name: Docker Compose Build and Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compose-build-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Run with Docker Compose
      run: |
        chmod +x docker/check/check.sh
        docker compose -f docker/check/docker-compose.yml up --build
    - name: Check container status
      run: |
        exit_status=$(docker inspect pandoc-1 --format='{{.State.ExitCode}}')
        if [ "$exit_status" != "0" ]; then
          echo "Container exited with error code $exit_status"
          exit $exit_status
        fi
    

